services:
  seaclear:
    build: .
    image: seaclear-replication:melodic
    container_name: seaclear
    privileged: true
    shm_size: "1gb"
    environment:
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - GALLIUM_DRIVER=llvmpipe
      - MESA_GL_VERSION_OVERRIDE=3.3
    volumes:
      - ./results:/root/results:rw
      - ./ros_ws/src:/root/ros_ws/src:rw
    ports:
      - "5900:5900"
      - "6080:6080"
    stdin_open: true
    tty: true
    command: bash
